function showMessages(day) {
    const messages = getMessagesForDay(day);

    const messagePage = window.open("", "_blank", "width=400,height=400");

    messagePage.document.write("<h2>Happy Birthday, my bebelabsugarplum!</h2>");
    messagePage.document.write("<u>Day" + day + "</u>");
    messagePage.document.write("<ul>");
    messages.forEach(element => {
        messagePage.document.write("<li>" + messages + "</li>");
    });
    messagePage.document.write("</ul>");
}

function getMessagesForDay(day) {
    const messages = [
        ["<h3>December 13,2023</h3> <p>First day ng pag write ko ng letter for your upcoming birthday babe hehe ka call kita now, ngayon na lang ulit tayo nakapag call kasi nawalan kayo ng wifi, and while im writing this nag uusap tayo about planning na mag chritstmas party pero dalawa lang tayo HAHAHAHA cute. Cute parang kanina lang aaway tayo tas ngayon sweet sweet na HAHAHAHA gulo natin babe eh, pero kahit ganito tayo, i still enjoy and appreciate how we manage this kind of fight (appreciate?! huy) HAHAHAHA.That all for now kasi may 1 month pa ako na isusulat, i love you so much babe, ikaw lang mamahalin.</p>"],
        ["<h3>December 14,2023</h3> <p>2nd day na ng pag write ko ng letterrr, 30 days before your birthday babe. So far ngayong araw wala tayong away (astiggg) di tayo nakapag away kasi busy ako kaninang umaga sa school kasi nga Christmas party HAHAHAHAHA pero sana later di na mag away (currently 10pm pa lang). Sakit mo babe, ayaw mo call, cry na ako dito sa gilid, di mo na ako love, iba na love mo (si oa talaga eh HAHAHAHA) joke lang babe. This day is like normal days lang natin, except walang away talaga HAHAHAHAA. scam pala, nag away pala tayo kasi na slide yung finger ko naging baby amp haha kasalanan ng firefly yon. 678 days since i started telling you 520, pero even before that mahal na mahal na kita, like what I've said dinedeny ko lang hehe. But now i wont deny it na, i love you so much, moon.</p>"],
        ["<h3>December 15,2023</h3> <p>3rd day of writing na babe, 29 days before your 20th birthday na. Nothing really happened ngayong araw nag plan lang tayo kung ano gagawin sa future house natin, and na busy na manood (pero mas na busy talaga ako sa panonood) then ngayong gabi, di ko alam on how would i explain this sagutan lang ba or what? Sorry ulit babe kung di ko ka man na meet expectation mo sakin, di ko na talaga alam yung ibang way on how to express it eh. Kahit na di ko masyado na eexpress babe, please just always think na mahal na mahal kita, i love you so much, binalikan kita babe kasi mahal na mahal na mahal kita</p>"],
        ["<h3>December 16,2023</h3> <p>4th daw na babeee, 28 days na lang babe, lapit na birthday moon. 680 days na kitang mahal, and mas mamahalin pa kita ng todo sa mga susunod na araw, di ko man masyado na eexpress pag mamalove ko sayo pero always know babe na mahal na mahal kita. Ang sweet natin ngayong araw babe walang away, kamanyakan lang meron HAHAHAHAH sana ganto everyday walang away, kaso wala namang thrill kaya boring, sige bwisitin na lang kita minsan hehe mwaaa. I love you so much babe, ikaw na last babe, ikaw lang.</p>"],
        ["<h3>December 17,2023</h3> <p>5th day na babee, 27 days na lang babeee. 2nd Monthsary natin ngayon, 1 year and 5 months na sana kung di nag break HAHAHAHA. 681 days since the first day i said 520 wowers, don't worry babe mas manimahal kita in every second na lumilipas. Wala naman nangyari ngayong araw, di naman tayo nag ceceleb eh HAHAHAHA. Amazing babe, di tayo nag away ngayong araw, the world is healing. Sorry babe di ako nakapag bati ng 11:59 for our last min monthsary, nakaidlip talaga eh, di na kinaya ng eyes. Mahal na mahal pa rin kita babe kahit wala ako natatanggap na letter every monthsary natin, mwamwaaaa. I love you so much, babe.</p>"],
        ["<h3>December 18,2023</h3> <p>6th day na babeee, 26 days to go na lang, lapit na birthday mo babee. 682 days na rin since nag sabi ako 520, pero i already love you before that. Yung plano natin kaninang madaling araw na magiging cold for a whole day hindi natuloy HAHAHAHA, hindi kinaya eh mahal na mahal mo ko eh mwamwa. Pagkagising ko pa lang non ng mga 7am gusto ko na sana ihug ka kaso naalala ko yung plan, edi natulog na lang ako ulit kasi magiging cold lang din naman HAHAHAHA ayon 9 na nagising. Ang sweet mo ngayong araw babe, kahit na nag away tayo dahil sa nasabi ko hehe sorry babe, di makaramdam minsan daliri ko eh, walang preno. Sorry ulit babe sa nasabi ko, na explain ko naman na kung bakit. I keep falling in love with you everyday, babe. i love you so much.</p>"],
        ["<h3>December 19,2023</h3> <p>wowers ikaw 7th day ko na nag susulat ng letter, i cant believe babe na kaya ko gumawa ng gantong bagay, eh dati lang hate na hate ko gumawa ng letter or essays HAHAHAHAHA iba talaga nagagawa ng inlove, i even tried drawing na alam mong hate ko rin kasi maikli lang pasensya ko HAHAHAHAHAHA. Ano ba ginawa mo sakin? ginayuma mo ako no? kidding aside babe, i love what im doing now, i love it when i think its for you naman. 25 days to go before your birthday, and im loving for more than 683 days since i started sending you 520 hehe sows in love na in love. Wala naman nangyari ngayong araw babe, binilhan lang kita ng sabon, and again wala na naman awaaaayyy yessss, the world is healing na talaga. Thank you babe for accepting me. i love you so much.</p>"],
        ["<h3>December 20,2023</h3> <p>ika 8th day na babe ng pag write ko ng letter, 24 days na lang din before your 20th birthday tanda na ikaw babeee, pero kahit old na ikaw babe, mahal na mahal pa rin kita. 684 days na rin babe since i sabi to you the 520. Today babe wala naman ganap, may nag chat lang sayo na peste kaya napikon ka HAHAHAHAHA, then nung hapon nag plan tayo manood ng the house of us kaso hindi natuloy, so nag play na lang tayo ng rat HAHAHAHAHA its fun babe kahit na masakit sa ulo, and nakakagulat sa una, which i know tawang tawa ka kasi natakot ako HAHAHAHAHA edi sorry matatakutin. i love you so much, trisha alexandra.</p>"],
        ["<h3>December 21,2023</h3> <p>9th day na babe nang pag sulat ng letterr, 23 days na lang din before your birthday. 685 na babe since nag sabi ako, ng 520, yet mahal na mahal pa rin kitaaa. Today update is wala naman nangyari ulit babe kasi we're both busy, ikaw busy ka sa paglinis ng room mo, while ako busy sa pag tinda sa tindahan, then this night babe di ko alam kung dinedeny mo lang na nagseselos ka or nagseselos ka na talaga kasi nakausap ko ex ko sa gc namin. You can always tell me naman babe if something is bothering you, your feelings is alwags valid, and i'll always try to fix it, okay? i love you always, babe.</p>"],
        ["<h3>December 22,2023</h3> <p>10 days na babe, shet this is not me talaga, imagine babe nakaya ko mag sulat ng letter in 10 consecutive days, kung yung dating sarili ko to, baka 2 days pa lang tinamad na ako AHAHHAAHA, wala eh iba epekto mo sakin, feeling ko talaga ginayuma mo ako. December 22 na babe, tas 22 days na lang din birthday mo na, astig parehas 22 hehe. 686 days and couting pa rin since nag sabi ako 520, ganon kita kamahal babe, mag 2 years na kitang mahal na mahal oh. Sayo lang mababaliw, sayo lang uuwi HAHAHAHAHA. Ngayong araw babe hehe wala ako sa mood eh kaya di nakapag usap nang matino, tapos ngayong gabi aba may paayuda ka babe, nag send ba naman ng videos, super hotttttt, ang ganda pa. i'm so lucky babe kasi sa out of all nag try manligaw sayo ako lang pinayagan mo, and may super laking bonus pa aba, sinagot pa nga shet bebelabsugarplum ko nga naman talaga. Mahal na mahal kita palagi babe, i love you so so very much, babe.</p>"],
        ["<h3>December 23,2023</h3> <p>11th day na babe nang pagsusulat, baka maging journalist na ako neto(huyy!) HAHAHAHAHA joke lang babe. 21 days na lang birthday mo na, shet lapit na babe, lapit na lang din graduate na tayo, pwede na kita puntahan hehe. 687 days and still counting pa rin syempre duhh, mahal na mahal kita eh, ikaw pa ba! ikaw na yan babe eh, si Trisha Alexandra Grecalda. May kasalanan pala ako ngayon babe, diba dapat dec 23 ko to sinusulat? hehe dec 24 na sa sobrang busy namin kanina, wala naubusan ako time para isulat to, hehe sorry babe. Ngayong araw babe, wala naman nangyari busy ulit tayo eh, tas nag decor ako ng christmas tree mo na sinend mo hehe pogi pogi ko doon. i love you so much, babe. ikaw lang mamahalin sa araw araw.</p>"],
        ["<h3>December 24,2023</h3> <p>12th day na of me writing a letter, hays journalist na talaga ako na letterist(?) kssi nag susulat ako ng letter HAHAHAHAHAHA, 20 days na lang babe 20th birthday mo na, parang nung kelan lang 18th birthday mo yung ni celeb natin, tas may pa myday ka pa ng convo natin na may ily sheesh, tas ngayon wala na? aba naman talaga, charot lang hehe di masama loob ko babe, joke lang yon hehe mwaaaa. Mahal na mahal pa rin kita as of 688 days since the day i told you 520, mahal na mahal pa rin kita babe kahit ang lakas palagi ng toyo and trip mo. Ngayong araw syempre busy na naman ako, nawalan ako ng time sayo, tapos nakstulog pa ako noong hapon, tas ngayon gabi aba naman nag away away pa HAHAHAHAHA pero mahal na mahal pa rin kita, babe. Mamahalin pa rin kita kahit araw araw mo pa ako awayin, di mag babago yon, pero syempre pag seselos ko di rin mawawala yan, habang buhay ako magseselos sa lahat ng nakakausap mo sa rp. i love you so much bebelabs mwamwa.</p>"],
        ["<h3>December 25,2023</h3> <p>13 days na ako babe nag susulat ng letterrr, 19 days na lang din babe 20 ka na, lapit ka na rin grumaduate shet dont leave me bebe. 689 days babe yet im dtill deeply inlove with you sheesh english ako langg to babe. Todays ganap is masaya naman babe yet malungkot din somehow, di tayo naka countdown ng sabay eh kasi nag eat ka, pero okay lang naman yon konti lang kinain mo non mag hapon ehhh, kaya okay lang yon kahit di tayo nakapag countdown ng sabay, tapos nong hapon naman babe we had an argument, di ko alam kung big or small argument lang yon kasi for me kalmado lang tayo, pero i'm really sorry babe kasi napaiyak na naman kita, nadala lang ako ng mga iniisip ko kaya napa open up na rin ako, tulad ng sabi ko babe walang mag bbreak, and mahal na mahal kita. Sayo lang palagi babalik, i love you so much.</p>"],
        ["<h3>December 26,2023</h3> <p>14 days na babe im a journalist n twlaga wala lang headline hehe. 18 days na lang babe birthday mo na, ang bilis naman ng araw parang nung nakaraan 30 days pa ahhh, di pa ako ready babe wala pa ying gift koo. 690 days of loving you so so much, im still addicted to you(addicted huyy) HAHAAHAHA. Kanina babe we had an argument ulit, pero we manage to fix it naman, and im proud cause me fought for it even though naiisip mo na makipag break pero hindi mo nagawa babe, im proud of you babe, my love for you have got even deeper (di ko na alam kung tama pa emglish ko, dont bash me babe) then babe nong hapon naging sweet kaaaa super sweet, i think the world is healing na talaga babe, im sorry babe for playing with them ulit ngayong gabi kahit na sinabi ko kanina umaga na di na ako makikipag laro, forgive me babe. I love you so much, babe.</p>"],
        ["<h3>December 27,2023</h3> <p>15th day na babe ng pag write ko ng message, dapat may sweldo na ako neto ehhh HAHAHAHA joke lang mwaa. 17 days na lang babe birthday mo naaaa, yung gift ko talaga di ko pa na rready shet im na ppressure na, pero okay lang hehe i have something na plan na, sabihin ko na lang 2 days before dito sa message hehe. 691 days na kitang mahal babe actually more than that pa pero mahal na mahal pa rin kitaaaa, adik na adik pa rin ako sayo oh kahit araw araw mo ako inaaway, ganon kita kamahal babe🫶. Ngayong araw babe, hindi naman busy pero hehe nag outing kasi kami babe and hindi tayo masyado nakapag usap kasi sabi mo mag enjoy lang ako, pero inuupdate pa rin naman kita, di ko lang alam if enough yon hehe, you can always call 09456745020 naman if you have a problem with that HAHAHAHAHAHA. And then ngayong gabi triny ko maging cold kasi bida bida ako, akala ko lalambingin ako ehhh inaway pala HAHAHAHAH pero okay lang mahal na mahal pa rin kita, kaya sinabayan ko na lang trip mo HAHAHAHAHA napikon ka tuloy bleeeh. I really enjoyed this day babe, thank you for letting me do whatever i want. I love you so so much, babe.</p>"],
        ["<h3>December 28,2023</h3> <p>16th day na babe nang pag write ko ng letter for your birthday. 16 days na lang din birthday mo na, hala same sa days ng pag write ko ng letter HAHAHAHAH astig. 692 days of loving you even more, grabe naman talaga ang gayuma na ginamit babe HAHAHAHAHA. Anyways, ano ba nangyari kaninang umaga? wala naman hehe triny ko lang gayahin yung way ng pagtatampo mo tapos di mo ako sinuyooo, tapos babe noong hapon hindi tayo nakapag usap kasi nag rest ikaw while nag babasa ng book, while ako hehe syempre nakatulog, then ngayong gabi i started my project na project code: birthday ni bebelabs HAHAHAHA kaya di rin kita nakausap masyado babe kasi im busy trying to figure out pano gawin yon kasi nga di pa natuturo samin, and self learning lang talaga ginagawa ko, but i managed to do it naman kahit hindi ganon kagandahan, babawi ako babe pag marunong na ako. i'll send this you babe sa birthday mo hehe. I love you so much, Trisha Alexandra Grecalda.</p>"],
        ["<h3>December 29,2023</h3> <p>pang ilang day na to? 17 naaaa, shet im a writer na talaga HAHAHAHA. 15 days na lang babe birthday mo naaa, next next week na babe, shet ang lapit naaa! Nasa point na ako babe kung itutuloy ko yung pagbili sayo ng bouquet for your birthday or hindi? kasi namannn, natatakot ako kay lola mo, baka pagalitan kaaaa, so pinag iisipan ko kung itutuloy ko or no, last December 12 pa ako nag hahanap ng shops malapit sainyo eh HAAHAHA remember nong tinanong kita kung malapit yung mga lugar sainyo? yon yong time. 693 days babe im still loving you sooo deeply (di ko na alam kung tama pa grammar ko hehe). Ngayon babe syempre we had an argument ulit, to the point nag aya ka na ng break up, pero we managed to fix it naman syempre, di ako papayag mag break no duh. I love you so much, babe.</p>"],
        ["<h3>December 30,2023</h3> <p>18th day na babeee, feeling ko talaga need ko na mag shift into journalist dahil dito HAHAHAHA joke lang, mas malaki pa rin sweldo ng IT kahit feeling ko pagkagrad ko wala na ako trabaho dahil sa mga AI HAHAHAHA pero dont worry babe, i'll work hard for our dreams (huy?! si english). 14 days na lang babe birthday mo na, exactly 2 weeks na lang, ang bilis ng araaaw 20 ka na babeee, pero prinsesa ka pa rin mwaaaa. 694 na babe of loving you, di pa rin ako magsasawang mahalin ka araw araw nang grabe, hinding hindi na kita iiwan ulit. Today ganap is na busy tayo noong morning babe kasi nag linis ka and nag prep kayo for christmas party, ghad kapitana nyo talaga walang kwenta. Tapos noong hapon babe hindi ko na maalala ano nangyari kasi napaka bilis ng oras aba, then noong gabi syempre asaran duh, and then babe we played telepathy game, sa ilang rounds nalaro natin 2 or 3 lang nahulaan natin ng pareho HAHAHAHAHA pero its okay babe, we enjoyed naman, and that's what is important. I love you with all my heart, babe.</p>"],
        ["<h3>December 31,2023</h3> <p>take 2 babe kasi na delete ko yung message ko, ang haba na non eh, tapos nakalimutan ko na sinulat ko. 19th day na babe of writing this letter, im sorry bab2 kung some of my typings is typo na kasi nakainom na ako, we just finished our call a while ago so you already know that we drank hehe. 13 days babe before your 20th birthday, i still feel pressured since the website thag i'm making is still not fully finish, i still have to learn more to finish that, but hop3fully i can finish that beofre your birthday, but if i cant finish it the way j wanted, i'll make bawi in the next project, i'll make more effort to learn how to that for you babe, i want you to be happy always, although we fight a lot this past few day, but my goal is to make you happy, sorry babe for the things that i have done this past few days, i wont ulit it again. 695 days and yet im still deeply inlove with you. Todays happening babe, we were both busy kasj nga you have bisitas, and we need to prep for the upcoming new year, its okay lang naman babe, kasi we both have our bahay ro accommodate. Babw, lahit na hindi na fulfill yung gusto ko na mag vc tayo and you sabi mo na mag vc tayo this new year, it's still okay lang babe, i'll wait for you until you are ready for that situatin. I love you so much babe, ikaw lang mamahalin palagi.</p>"],
        ["<h3>January 1,2024</h3> <p>20 days of writing na, konti na lang matatapos na babee. 12 days na lang babe birthday mo na, next week na yon shet 20 ka na. 696 na babe of loving youuu, mahal na mahal pa rin kita kahit wala ka sa mood ngayon HAHAHAHAH naalimpungatan eh. Today babe we celebrate together the ano the new year, tapos we count down together kahit na hindi na tumama pag countdown ko sa pagmamadali HAHAHAHAHA pero naka call naman tayo kaya okay lang HAHAHAHA sobrang ingay sainyo babe, sa sunod talaga sainyo na ako makiki celebrate HAHAHAHA. 3 years na tayo nag ccelebrate ng new year nang mag kasama, dapat pag 70+ years old na tayo magkasama pa rin tayo mag celebrate babe ah? pag hindi, edi dont, doon ka sa far away. Kidding aside babe HAHAHAHA i really want to spend all my new years with you na. New year, but still you, and will always be with you. I love you so much, babe.</p>"],
        ["<h3>January 2,2024</h3> <p>21 days na babe of writingg, tapos 10 days na lang birthday mo na, na pressure na talaga ako kasi yung code di ko pa naaayos HAHAHAHAHA edi sorry, bukas gagawin ko na talaga. 697 days babe mahal na mahal pa rin kita, nag bago kasi syempre mas minahal kita lalo, ikaw na yan eh, dapat mamahalin ng sobra sobraaa. Ngayon babe hehe sarap aga aga mo pa ako nilambing, tapos nong hapon babe umalis ako kasi dumalaw ako sa patay, tapos nong gabi hehe nag play ako babe, then i helped you review for your exam tomorrow, di ko lang sure kung naka help ako kasi puro tayo tawa HAHAHAHAHA and then we played among us HAHAHAHA kahit ako yung impostor hindi sinasabi eh, supportive girlfriend yan? HAHAHAHA. I love you with all my heart, babe.</p>"],
        ["<h3>January 3,2024</h3> <p>22 days na babe of writingg, cant wait to send you this na, i still cant believe na nagawa ko to araw arawin HAHAHAHA. 9 days na lang babe birthday mo na, next week na yon shet, 20 ka na next week babe, pero baby ka pa rin, and prinsesa pa rin ni papa HAHAHAHA cute cute. 698 na babe of loving you, lapit na mag 2 years babe HAHAHAHA. Its our monthsary today babe, and unfortunately hehe nawala sa isip ko kasi we were both busy playing, then yung iniisip ko na monthsary natin is 17 tsaka hehe nabusy rin ako kakaisip about sa up coming birthday mo kaya sorry ulit babe. We didn't really got to celebrate it kasi you were at school, and samin is brownout like letse kaya di ako makatawag and makapag spend time sayo, ni pplan ko pa naman sana ngayon tayo manood ng movie. Sa birthday mo na lang babe, babawi ako, i'll make sure of that. I love you so so much, my girlfriend.</p>"],
        ["<h3>January 4,2024</h3> <p>23 days na babe of sulating thiss, then 8 days na lang din babe birthday mo na, lapit na talagaaa, yung gifts ko sayo di ko mabigay, yung website labg siguro mabibigay ko ngayon, nakakatakot kasi si lola babe. 699 days babe, mahal na mahal kita, ikaw lang hanggang huli babe. Ngayon babe, di tayo masyado nakapag usap kasi may pasok ako, then noong hapon brownout babe, pero buti naman nagkailaw na nonv mga 7, tapos babe nagkasagutan pa kami nila lala kasi mga nag mamagaling sila, then we had a call babe kaso inoff naman wifi nyo, pero im happy kasi na hear ko voice mo. I'm so lucky to have babe, thank you for choosing me. I love you with all my heart and mind, babe.</p>"],
        ["<h3>January 5,2024</h3> <p>Nag aaway tayo ngayon babe hehe, di ko rin alam bakit, bigla na lang ikaw nawala sa mood eh, feeling ko mood swings mo kasi malapit na period mo, kahit malakas topak mo babe mahal na mahal kita. Ikaw lang pipiliin kung may pagpipilian man. 24 days na pala ako nag susulat, malapit na matapos, 7 days na lang kasi birthday mo na, 1 week na lang yon babe, kung wala lang talaga si lola bibigay ko yung bouquet ehh, kaso tatakot ako hehe. 700 days of loving you still, wow tagal na almost 2 years na, ang bilis namann. Will still love you more for each year we spend together (wag mo bash english ko). Ngayon babe wala naman talaga nangyari, ang sweet sweet mo nong umaga, then ngayong gabi inaway na ako HAHAHAHAHAHA mahal na mahal kita babe, kahit grabe talaga mood swings mo minsan HAHAHAHA. I love you 3000, babe.</p>"],
        ["<h3>January 6,2024</h3> <p>kakatapos ko lang mag cry babe kasi nag away tayo hehe, tas rinig mo pala sa call. Sorry babe kung ano man nagawa ko noon, di ko rin alam babe bakit ko nagawa yon, di ko sadya yon babe. 25th day of writing, and 6 days na lang babe birthday mo na, lapit lapit na babe, remember kanina babe bakit bigla ako nawala? hehe nag hahanap ako ng flower shops non na malapit sainyo, kaso wala eh. Kaya iba na lang gagawin ko, and sa susunod ko pa mabibigay kasi wala nang time babe. I really want to give you some flowers babe, but everytime maalala ko na strict si lola, natatakot ako eh, baka bigla na lang kita di makausap pag nalaman nila. Then noong hapon babe, tinuloy ko na yung code, kasi kahit doon na lang makabawi ako kasi kukang yung supposed to be na gift ko for you. Malapit na sya matapos babe, di ko lang alam kung bet mo yung magiging color pallete, still not good with it eh. 701 days babe, mahal na mahal pa rin kita, more than sa pag mamahal ko sayo since i said that. Ikaw lang mamahalin babe, and ikaw na ang huling mamahalin. Mahal na mahal kita, babe.</p>"],
        ["<h3>January 7,2024</h3> <p>Kakatapos lang natin babe mag review, and effectivee kasi mas natatandaan ko. Thank you for helping me, babe. 26th day na babe of writing, and 5 days na lang babe birthday mo na, ang lapit na babe 20 ka na sa saturday, okay lang yan babe, baby ka pa rin naman nila papa, and i will still spoil you. 702 days babe, still loving you more and more everyday, babe. So kanina babe hehe, buong hapon ako wala kasi nag code hehe, may improvement na babe yung code, everyday mas na eexcite ako tapusin yung code, kasi gusto ko na makita mo yung code, and i also want to see your reaction. Then noong umaga pala babe, i think may idea ka na kung bakit tanong ako nang tanong about sa necklace and bracelet ng mikana hehe, nag hahanap na kasi ako ng pang gift ko sayo kasi nga di matuloy yung bouquet. Than ngayon gabi babe wala ulit ako time kasi hanggang 10pm nag ccode pa rin ako hehe, tapos tinulungan mo ko mag review for our quiz tomorrow, ang thank you babe, its a big help kasi mas naintindihan ko lalo yung lesson. I love you with all my heart and brain, babe.</p>"],
        ["<h3>January 8,2024</h3> <p>We're on call right now while im writing this 27th letter for a month na babe, tagal tagal ko na susulat, 1 month din HAHAHAHAHA well you deserve this naman babe, i know you like letters more than flowers kaya kahit kinakabahan din ako sa outcome ng letter code na to, ippursue ko pa rin kasi i know you like reading letters, mag sawa ka babe sa 31 letters HAHAHAHAHA. 4 days na lang babe birthday mo na, yet di ko pa tapos ifinalise yung code ko, madami ng errors nangyari kaya i was so busy during the day, kahit konti lang yung progress na nangyari, ang dami talagang errors HAHAHAHA pero for you to kaya i'll make it special kahit na self learn lang ako. 703 days na kitang mahal na mahal babe, di pa rin nag babago, ikaw pa rin mahal ko since first day, mas minamahal pa kita everyday. Sorry kanina babe, nawalan na ako ng time kasi nag focus talaga babe sa coding, you know kaartehan ko kahit hindi ako artistic HAHAHAHAHA sabi mo pa kanina hindi mo ako kakausapin para matapos ko na and masubmit ko na, di mo lang alam sayo ko talaga ipapasa yon HAHAHAHAHA. i love you with all my heart for the rest of my life, babe.</p>"],
        ["<h3>January 9,2024</h3> <p>i want to call you, kaso hindi pwede kasi katabi mo kapatid mo babe, and tulog na. Pero okay lang naman hehe, may bukas pa naman, we can have a call naman sa saturday, sa birthday mo babe, which is 3 days from now, palapit nang palapit na birthday mo babe, and 20 ka naaa, pero okay lang mahal na mahal pa rin kita kahit mukhang 2 years gap na tayo HAHAHAHAHA. Its my 28th day of writing a message babe, i hope you can appreciate this kahit di ko alam kung san patungo mga pinag susulat ko hehe. Im already loving you for 704 days, konti na lang talava 2 years na, everyday na mag pass mas lalo lang kita minamahal, and mas mamahalin ka pa lalo sa mga dadating na araw, buwan, and taon. Di tayo masyado nakapag uaap ngayon babe kasi may pasok ako, then nag code din ako nang konti kanina pero ang bilis ng oras kaya nawalan ako ng time, sorry for not having a good time management, babe. i love you with all my heart, babe.</p>"],
        ["<h3>January 10,2024</h3> <p>Been writing for 29 days already, and malapit na matapos to babe ginagawa ko, i really hope na magustuhan mo to. 2 days na lang babe birthday mo na, 20 ka na babe, malapit ka na rin grumaduate, it means malapjt na rin kita makita hehehehe, excited na akoooo, gusto na kita makasama babe, mag airbnb tayo diba tapos 3 days and 2 nights, pero baka di na talaga kita iuwi hehe mwaaa. 705 days na kitang mahal na mahal babe, may plano ka pang hiwalayan ako nyan? aba naman, wag naman sana. Kaninang morning ko pala babe inorder yung necklace and bracelet, sana magustuhan mo yon hehe, di ko inexpect na ma ship out kaagad, ghad. Kaya ayon baka bukas babe or sa friday nandyan na yung gift ko na dapat sa 13 ko ibibigay, kaso napaka excited naman iship outt. The rest of the day hehe busy ako, nag practice kasi eh, dami dami arte ng pe. Rest assured babe na sayo pa rin ako, and walang maghihiwalay kahit na nag bigay ako ng accessories. I love you so much, and will love you for the rest of our lives.</p>"],
        ["<h3>January 11,2024</h3> <p></p>"],
        ["<h3>January 12,2024</h3> <p></p>"],
        ["<h3>January 13,2024</h3> <p></p>"],


    ];

    if (day >=1 && day <= messages.length) {
        return messages[day - 1];
    } else {
        return["no"];
    }
}
