function showMessages(day) {
    const messages = getMessagesForDay(day);

    const messagePage = window.open("", "_blank", "width=400,height=400");

    messagePage.document.write("<h2>Happy Birthday, my bebelabsugarplum1</h2>");
    messagePage.document.write("<u>Day" + day + "</u>");
    messagePage.document.write("<ul>");
    messages.forEach(element => {
        messagePage.document.write("<li>" + messages + "</li>");
    });
    messagePage.document.write("</ul>");
}

function getMessagesForDay(day) {
    const messages = [
        ["<h3>December 13,2023</h3> <p>First day ng pag write ko ng letter for your upcoming birthday babe hehe ka call kita now, ngayon na lang ulit tayo nakapag call kasi nawalan kayo ng wifi, and while im writing this nag uusap tayo about planning na mag chritstmas party pero dalawa lang tayo HAHAHAHA cute. Cute parang kanina lang aaway tayo tas ngayon sweet sweet na HAHAHAHA gulo natin babe eh, pero kahit ganito tayo, i still enjoy and appreciate how we manage this kind of fight (appreciate?! huy) HAHAHAHA.That all for now kasi may 1 month pa ako na isusulat, i love you so much babe, ikaw lang mamahalin.</p>"],
        ["<h3>December 14,2023</h3> <p>2nd day na ng pag write ko ng letterrr, 30 days before your birthday babe. So far ngayong araw wala tayong away (astiggg) di tayo nakapag away kasi busy ako kaninang umaga sa school kasi nga Christmas party HAHAHAHAHA pero sana later di na mag away (currently 10pm pa lang). Sakit mo babe, ayaw mo call, cry na ako dito sa gilid, di mo na ako love, iba na love mo (si oa talaga eh HAHAHAHA) joke lang babe. This day is like normal days lang natin, except walang away talaga HAHAHAHAA. scam pala, nag away pala tayo kasi na slide yung finger ko naging baby amp haha kasalanan ng firefly yon. 678 days since i started telling you 520, pero even before that mahal na mahal na kita, like what I've said dinedeny ko lang hehe. But now i wont deny it na, i love you so much, moon.</p>"],
        ["<h3>December 15,2023</h3> <p>3rd day of writing na babe, 29 days before your 20th birthday na. Nothing really happened ngayong araw nag plan lang tayo kung ano gagawin sa future house natin, and na busy na manood (pero mas na busy talaga ako sa panonood) then ngayong gabi, di ko alam on how would i explain this sagutan lang ba or what? Sorry ulit babe kung di ko ka man na meet expectation mo sakin, di ko na talaga alam yung ibang way on how to express it eh. Kahit na di ko masyado na eexpress babe, please just always think na mahal na mahal kita, i love you so much, binalikan kita babe kasi mahal na mahal na mahal kita</p>"],
        ["<h3>December 16,2023</h3> <p>4th daw na babeee, 28 days na lang babe, lapit na birthday mooo. 680 days na kitang mahal, and mas mamahalin pa kita ng todo sa mga susunod na araw, di ko man masyado na eexpress pag mamalove ko sayo pero always know babe na mahal na mahal kita. Ang sweet natin ngayong araw babe walang away, kamanyakan lang meron HAHAHAHAH sana ganto everyday walang away, kaso wala namang thrill kaya boring, sige bwisitin na lang kita minsan hehe mwaaa. I love you so much babe, ikaw na last babe, ikaw lang.</p>"],
        ["<h3>December 17,2023</h3> <p>5th day na babee, 27 days na lang babeee. 2nd Monthsary natin ngayon, 1 year and 5 months na sana kung di nag break HAHAHAHA. 681 days since the first day i said 520 wowers, don't worry babe mas manimahal kita in every second na lumilipas. Wala naman nangyari ngayong araw, di naman tayo nag ceceleb eh HAHAHAHA. Amazing babe, di tayo nag away ngayong araw, the world is healing. Sorry babe di ako nakapag bati ng 11:59 for our last min monthsary, nakaidlip talaga eh, di na kinaya ng eyes. Mahal na mahal pa rin kita babe kahit wala ako natatanggap na letter every monthsary natin, mwamwaaaa. I love you so much, babe.</p>"],
        ["<h3>December 18,2023</h3> <p>6th day na babeee, 26 days to go na lang, lapit na birthday mo babee. 682 days na rin since nag sabi ako 520, pero i already love you before that. Yung plano natin kaninang madaling araw na magiging cold for a whole day hindi natuloy HAHAHAHA, hindi kinaya eh mahal na mahal mo ko eh mwamwa. Pagkagising ko pa lang non ng mga 7am gusto ko na sana ihug ka kaso naalala ko yung plan, edi natulog na lang ako ulit kasi magiging cold lang din naman HAHAHAHA ayon 9 na nagising. Ang sweet mo ngayong araw babe, kahit na nag away tayo dahil sa nasabi ko hehe sorry babe, di makaramdam minsan daliri ko eh, walang preno. Sorry ulit babe sa nasabi ko, na explain ko naman na kung bakit. I keep falling in love with you everyday, babe. i love you so much.</p>"],
        ["<h3>December 19,2023</h3> <p>wowers ikaw 7th day ko na nag susulat ng letter, i cant believe babe na kaya ko gumawa ng gantong bagay, eh dati lang hate na hate ko gumawa ng letter or essays HAHAHAHAHA iba talaga nagagawa ng inlove, i even tried drawing na alam mong hate ko rin kasi maikli lang pasensya ko HAHAHAHAHAHA. Ano ba ginawa mo sakin? ginayuma mo ako no? kidding aside babe, i love what im doing now, i love it when i think its for you naman. 25 days to go before your birthday, and im loving for more than 683 days since i started sending you 520 hehe sows in love na in love. Wala naman nangyari ngayong araw babe, binilhan lang kita ng sabon, and again wala na naman awaaaayyy yessss, the world is healing na talaga. Thank you babe for accepting me. i love you so much.</p>"],
        ["<h3>December 20,2023</h3> <p>ika 8th day na babe ng pag write ko ng letter, 24 days na lang din before your 20th birthday tanda na ikaw babeee, pero kahit old na ikaw babe, mahal na mahal pa rin kita. 684 days na rin babe since i sabi to you the 520. Today babe wala naman ganap, may nag chat lang sayo na peste kaya napikon ka HAHAHAHAHA, then nung hapon nag plan tayo manood ng the house of us kaso hindi natuloy, so nag play na lang tayo ng rat HAHAHAHAHA its fun babe kahit na masakit sa ulo, and nakakagulat sa una, which i know tawang tawa ka kasi natakot ako HAHAHAHAHA edi sorry matatakutin. i love you so much, trisha alexandra.</p>"],
        ["<h3>December 21,2023</h3> <p>9th day na babe nang pag sulat ng letterr, 23 days na lang din before your birthday. 685 na babe since nag sabi ako, ng 520, yet mahal na mahal pa rin kitaaa. Today update is wala naman nangyari ulit babe kasi we're both busy, ikaw busy ka sa paglinis ng room mo, while ako busy sa pag tinda sa tindahan, then this night babe di ko alam kung dinedeny mo lang na nagseselos ka or nagseselos ka na talaga kasi nakausap ko ex ko sa gc namin. You can always tell me naman babe if something is bothering you, your feelings is alwags valid, and i'll always try to fix it, okay? i love you always, babe.</p>"],
        ["<h3>December 22,2023</h3> <p>10 days na babe, shet this is not me talaga, imagine babe nakaya ko mag sulat ng letter in 10 consecutive days, kung yung dating sarili ko to, baka 2 days pa lang tinamad na ako AHAHHAAHA, wala eh iba epekto mo sakin, feeling ko talaga ginayuma mo ako. December 22 na babe, tas 22 days na lang din birthday mo na, astig parehas 22 hehe. 686 days and couting pa rin since nag sabi ako 520, ganon kita kamahal babe, mag 2 years na kitang mahal na mahal oh. Sayo lang mababaliw, sayo lang uuwi HAHAHAHAHA. Ngayong araw babe hehe wala ako sa mood eh kaya di nakapag usap nang matino, tapos ngayong gabi aba may paayuda ka babe, nag send ba naman ng videos, super hotttttt, ang ganda pa. i'm so lucky babe kasi sa out of all nag try manligaw sayo ako lang pinayagan mo, and may super laking bonus pa aba, sinagot pa nga shet bebelabsugarplum ko nga naman talaga. Mahal na mahal kita palagi babe, i love you so so very much, babe.</p>"],
        ["<h3>December 23,2023</h3> <p>11th day na babe nang pagsusulat, baka maging journalist na ako neto(huyy!) HAHAHAHAHA joke lang babe. 21 days na lang birthday mo na, shet lapit na babe, lapit na lang din graduate na tayo, pwede na kita puntahan hehe. 687 days and still counting pa rin syempre duhh, mahal na mahal kita eh, ikaw pa ba! ikaw na yan babe eh, si Trisha Alexandra Grecalda. May kasalanan pala ako ngayon babe, diba dapat dec 23 ko to sinusulat? hehe dec 24 na sa sobrang busy namin kanina, wala naubusan ako time para isulat to, hehe sorry babe. Ngayong araw babe, wala naman nangyari busy ulit tayo eh, tas nag decor ako ng christmas tree mo na sinend mo hehe pogi pogi ko doon. i love you so much, babe. ikaw lang mamahalin sa araw araw.</p>"],
        ["<h3>December 24,2023</h3> <p>12th day na of me writing a letter, hays journalist na talaga ako na letterist(?) kssi nag susulat ako ng letter HAHAHAHAHAHA, 20 days na lang babe 20th birthday mo na, parang nung kelan lang 18th birthday mo yung ni celeb natin, tas may pa myday ka pa ng convo natin na may ily sheesh, tas ngayon wala na? aba naman talaga, charot lang hehe di masama loob ko babe, joke lang yon hehe mwaaaa. Mahal na mahal pa rin kita as of 688 days since the day i told you 520, mahal na mahal pa rin kita babe kahit ang lakas palagi ng toyo and trip mo. Ngayong araw syempre busy na naman ako, nawalan ako ng time sayo, tapos nakstulog pa ako noong hapon, tas ngayon gabi aba naman nag away away pa HAHAHAHAHA pero mahal na mahal pa rin kita, babe. Mamahalin pa rin kita kahit araw araw mo pa ako awayin, di mag babago yon, pero syempre pag seselos ko di rin mawawala yan, habang buhay ako magseselos sa lahat ng nakakausap mo sa rp. i love you so much bebelabs mwamwa.</p>"],
        ["<h3>December 25,2023</h3> <p>13 days na ako babe nag susulat ng letterrr, 19 days na lang din babe 20 ka na, lapit ka na rin grumaduate shet dont leave me bebe. 689 days babe yet im dtill deeply inlove with you sheesh english ako langg to babe. Todays ganap is masaya naman babe yet malungkot din somehow, di tayo naka countdown ng sabay eh kasi nag eat ka, pero okay lang naman yon konti lang kinain mo non mag hapon ehhh, kaya okay lang yon kahit di tayo nakapag countdown ng sabay, tapos nong hapon naman babe we had an argument, di ko alam kung big or small argument lang yon kasi for me kalmado lang tayo, pero i'm really sorry babe kasi napaiyak na naman kita, nadala lang ako ng mga iniisip ko kaya napa open up na rin ako, tulad ng sabi ko babe walang mag bbreak, and mahal na mahal kita. Sayo lang palagi babalik, i love you so much.</p>"],
        ["<h3>December 26,2023</h3> <p>14 days na babe im a journalist n twlaga wala lang headline hehe. 18 days na lang babe birthday mo na, ang bilis naman ng araw parang nung nakaraan 30 days pa ahhh, di pa ako ready babe wala pa ying gift koo. 690 days of loving you so so much, im still addicted to you(addicted huyy) HAHAAHAHA. Kanina babe we had an argument ulit, pero we manage to fix it naman, and im proud cause me fought for it even though naiisip mo na makipag break pero hindi mo nagawa babe, im proud of you babe, my love for you have got even deeper (di ko na alam kung tama pa emglish ko, dont bash me babe) then babe nong hapon naging sweet kaaaa super sweet, i think the world is healing na talaga babe, im sorry babe for playing with them ulit ngayong gabi kahit na sinabi ko kanina umaga na di na ako makikipag laro, forgive me babe. I love you so much, babe.</p>"],
        ["<h3>December 27,2023</h3> <p>15th day na babe ng pag write ko ng message, dapat may sweldo na ako neto ehhh HAHAHAHA joke lang mwaa. 17 days na lang babe birthday mo naaaa, yung gift ko talaga di ko pa na rready shet im na ppressure na, pero okay lang hehe i have something na plan na, sabihin ko na lang 2 days before dito sa message hehe. 691 days na kitang mahal babe actually more than that pa pero mahal na mahal pa rin kitaaaa, adik na adik pa rin ako sayo oh kahit araw araw mo ako inaaway, ganon kita kamahal babe🫶. Ngayong araw babe, hindi naman busy pero hehe nag outing kasi kami babe and hindi tayo masyado nakapag usap kasi sabi mo mag enjoy lang ako, pero inuupdate pa rin naman kita, di ko lang alam if enough yon hehe, you can always call 09456745020 naman if you have a problem with that HAHAHAHAHAHA. And then ngayong gabi triny ko maging cold kasi bida bida ako, akala ko lalambingin ako ehhh inaway pala HAHAHAHAH pero okay lang mahal na mahal pa rin kita, kaya sinabayan ko na lang trip mo HAHAHAHAHA napikon ka tuloy bleeeh. I really enjoyed this day babe, thank you for letting me do whatever i want. I love you so so much, babe.</p>"],
        ["<h3>December 28,2023</h3> <p></p>"],
        ["<h3>December 29,2023</h3> <p></p>"],
        ["<h3>December 30,2023</h3> <p></p>"],
        ["<h3>December 31,2023</h3> <p></p>"],
        ["<h3>January 1,2024</h3> <p></p>"],
        ["<h3>January 2,2024</h3> <p></p>"],
        ["<h3>January 3,2024</h3> <p></p>"],
        ["<h3>January 4,2024</h3> <p></p>"],
        ["<h3>January 5,2024</h3> <p></p>"],
        ["<h3>January 6,2024</h3> <p></p>"],
        ["<h3>January 7,2024</h3> <p></p>"],
        ["<h3>January 8,2024</h3> <p></p>"],
        ["<h3>January 9,2024</h3> <p></p>"],
        ["<h3>January 10,2024</h3> <p></p>"],
        ["<h3>January 11,2024</h3> <p></p>"],
        ["<h3>January 12,2024</h3> <p></p>"],
        ["<h3>January 13,2024</h3> <p></p>"],
    ];

    if (day >=1 && day <= messages.length) {
        return messages[day - 1];
    } else {
        return["no"];
    }
}